# Generated by Django 4.2.14 on 2024-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_player_boosts_player_prizes_player_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='prizes',
            field=models.ManyToManyField(null=True, related_name='players', to='testapp.prize'),
        ),
    ]
